export const THEMES = [
  
  { name: "nuzzle", font: "'Sour Gummy', 'Inter', Arial, sans-serif" }, // Default theme
 
  { name: "dark", font: "'Roboto Mono', monospace" },
  { name: "cupcake", font: "'Comic Sans MS', cursive, sans-serif" },
  { name: "bumblebee", font: "'Montserrat', Arial, sans-serif" },
  { name: "emerald", font: "'Nunito', Arial, sans-serif" },
  { name: "corporate", font: "'Open Sans', Arial, sans-serif" },
  { name: "synthwave", font: "'Orbitron', Arial, sans-serif" },
  { name: "retro", font: "'VT323', monospace" },
  { name: "cyberpunk", font: "'Share Tech Mono', monospace" },
  { name: "valentine", font: "'Dancing Script', cursive" },
  { name: "halloween", font: "'Creepster', cursive" },
  { name: "garden", font: "'Quicksand', Arial, sans-serif" },
  { name: "forest", font: "'Merriweather', serif" },
  { name: "aqua", font: "'Lato', Arial, sans-serif" },
  { name: "lofi", font: "'Fira Mono', monospace" },
  { name: "pastel", font: "'Baloo 2', cursive" },
  { name: "fantasy", font: "'Paprika', cursive" },
  { name: "wireframe", font: "'Source Code Pro', monospace" },
  { name: "black", font: "'Oswald', Arial, sans-serif" },
  { name: "luxury", font: "'Playfair Display', serif" },
  { name: "dracula", font: "'JetBrains Mono', monospace" },
  { name: "cmyk", font: "'Barlow', Arial, sans-serif" },
  { name: "autumn", font: "'Muli', Arial, sans-serif" },
  { name: "business", font: "'IBM Plex Sans', Arial, sans-serif" },
  { name: "acid", font: "'Bangers', cursive" },
  { name: "lemonade", font: "'Fredoka One', cursive" },
  { name: "night", font: "'Space Mono', monospace" },
  { name: "coffee", font: "'Merriweather', serif" },
  { name: "winter", font: "'Cabin', Arial, sans-serif" },
  { name: "dim", font: "'Work Sans', Arial, sans-serif" },
  { name: "nord", font: "'Rubik', Arial, sans-serif" },
  { name: "sunset", font: "'Pacifico', cursive" },
];
